#
# YAML file configuring the actions to take when releasing to production
#
# > Syntax tips here: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#
name: Generate listing

on:
  workflow_dispatch:
    logLevel:
      description: 'Log level'
      required: true
      default: 'warning'
      type: choice
      options:
        - info
        - warning
        - debug

jobs:
  build-and-run-discovery:
    name: Discover new sources

    runs-on: ubuntu-latest
    permissions:
      contents: write

    concurrency:
      group: ${{ github.workflow }}-discovery
      cancel-in-progress: true

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Create UV installation"
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.9.13"

      - name: Installing packages
        run: uv sync --group=scripts

      - name: Running discovery
        run: make discover
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Skipping authentication on Gitlab for now
          # GITLAB_ACCESS_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          # Name of the artifact to upload.
          # Optional. Default is 'artifact'
          name: discovered_listings
          path: indexes/*
          retention-days: 60
